Remove default template
aemsites/hubblehomes-com pull request #149
Opened 2024-07-08 15:01 UTC by bhellema

Fix #148 

Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/news
- After: https://issue-148--hubblehomes-com--aemsites.hlx.live/news

2024-07-09 18:02 UTC, codevoyage commented on templates/default/default.js
> -import buildBreadcrumbs from '../../scripts/breadcrumbs.js';
Default.js was only used for adding the breadcrumbs?

2024-07-09 18:07 UTC, codevoyage commented
In the before/after pages linked above, the “Before” page has the breadcrumb, but the “After” page doesn’t. Is that the intended behavior?

2024-07-09 19:09 UTC, codevoyage requested changes
In the before/after pages linked above, the “Before” page has the breadcrumb in the right spot, but the “After” page has the breadcrumb above the carousel, please check.

2024-07-09 20:19 UTC, bhellema commented
> In the before/after pages linked above, the “Before” page has the breadcrumb in the right spot, but the “After” page has the breadcrumb above the carousel, please check.

I've pushed a change, can you please verify again.

2024-07-09 21:17 UTC, codevoyage commented on blocks/breadcrumbs/breadcrumbs.js
Since this is not an authorable block, this should be under the Template blocks.

2024-07-09 21:24 UTC, codevoyage commented on templates/communities/communities.js
> +  breadcrumb.remove();
Is the breadcrumb getting removed? Can you give an example of a sold-out community page?

2024-07-10 11:12 UTC, bhellema commented on blocks/breadcrumbs/breadcrumbs.js
Yeah I can move it to the template folder, it's not used per-say by templates but at least we will be consistent.

2024-07-10 13:56 UTC, merged