Shimahaj
aemsites/hubblehomes-com pull request #27
Opened 2024-05-21 01:03 UTC by codevoyage

Non-autoblocked version of the banner. Draft PR

Fix https://github.com/aemsites/hubblehomes-com/issues/9

Test URLs:
- Before: https://www.hubblehomes.com/
- After: https://shimahaj--hubblehomes-com--aemsites.hlx.page/drafts/shimahaj/document

2024-05-21 14:21 UTC, varunmitra requested changes
@codevoyage please clean up this PR. There are 35 files listed here. Please merge the latest changes from the main branch

2024-05-21 14:26 UTC, varunmitra requested changes
<img width="1285" alt="Screenshot 2024-05-21 at 10 19 13 AM" src="https://github.com/aemsites/hubblehomes-com/assets/12259186/455fbeb8-5cd1-4cc9-9dfe-7a19f6798b1f">
There is a slight mis match for the form `:focus` element state. Original form element has the following styling:
 `.form-control:focus {
    border-color: #66afe9;
    outline: 0;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 8px rgba(102, 175, 233, .6);`

2024-05-21 15:34 UTC, codevoyage commented
> @codevoyage please clean up this PR. There are 35 files listed here. Please merge the latest changes from the main branch

Yes, sorry about that. I've cleaned it up and merged the latest changes from the main branch.

2024-05-22 12:32 UTC, bhellema commented on blocks/banner/banner.css
> +.banner .spotlight-form-button {
I believe the hubblehomes.com button has a border-radius of 0px;
![Uploading image.png…]()

2024-05-22 15:01 UTC, closed without merging